### ISSUE TITLE
OpenCPN 3.2.2 Support

### ISSUE THREAD

**Issue by goodanchorage** [goodanchorage/goodanchorage_pi#8]
Recompile against 3.2.2. Several users complained.

**Comment by rgleason** [comment]
In goodanchorage_pi.h
#include "version.h"
#define     MY_API_VERSION_MAJOR    1
#define     MY_API_VERSION_MINOR    12

Please refer to the OpenCPN Developer Manual re  Plugin API Numbers
http://opencpn.org/ocpn/node/233
Note that with the following API:
pi110 (1.10)  =  OpenCPN 3.3.x (under design and development now).
pi110  (1.10) = OpenCPN 3.4
pi111 (1.11) = OpenCPN 3.4
pi112 (1.12) = OpenCPN 3.4
Would be compiled as Version 4.0 using the opencpn.lib from version 4.0 since all of these versions were beta versions and 4.0 is now out.
If you can change your api number back to 1.9  and it will compile with that opencpn.lib without lib errors then it can be done.

**Comment by rgleason** [comment]
Note: I tried to change the opencpn.lib from the version used in 4.0 to the version used in 3.2.2, and it did compile without errors, for Windows.  However your API Version is still 1.12 which is misleading and should be changed. Does it compile for Linux etc with that change?  Please advise.

**Comment by rgleason** [comment]
I will upload to Opencpn Beta File thingie as a version 3.2.2, but the api version should be changed.

**Comment by goodanchorage** [comment]
Unless I'm missing something, I'm afraid that 3.2.2 compatibility is a dead-end. The plugin depends on MouseEventHook method, which was defined in opencpn_plugin_112, which is API_VERSION_MINOR 12, isn't it?

Just to make sure I tried to change it down to:
#define MY_API_VERSION_MINOR 9
Recompiled and tried the plugin under 4.0 -- it doesn't work at all.

**Comment by rgleason** [comment]
So what do you suggest?

**Comment by rgleason** [comment]
It seemed to work for me.

**Comment by goodanchorage** [comment]
The double-click to view the list, and right-click to view details works? By all means, yes, please compile a 3.2.2 version. I'd love to try it out. Will change the code to #define MY_API_VERSION_MINOR 9 right away.

**Comment by goodanchorage** [comment]
Pushed the change.

**Comment by nohal** [comment]
Please, roll that change back, it is a total nonsense.
You are inheriting from `opencpn_plugin_112` and using stuff that did not exist in OpenCPN 3.2.2 - this plugin can never work with it.
@rgleason - Rick, I really don't know what you built, but it sure isn't what you think it is. Look at https://github.com/goodanchorage/goodanchorage_pi/blob/master/src/ocpn_plugin.h#L497 - That it builds with opencpn.lib from version 3.2 is simply impossible.

**Comment by goodanchorage** [comment]
Ahaha, here comes the smack-down. I rolled-back the change.

Thanks for chiming in Pavel.

**Comment by goodanchorage** [comment]
Let's just call 3.2.2 attempt a dead-end. It was worth a try but the users have to migrate to 4.0 at some point anyway.

Thank you both!

**Comment by rgleason** [comment]
If Pavel says it won't work, I would believe him.
I will mess with it, but roll back to the previous 4.0 version compiled earlier.  Who the devil asked for 3.2.2? I am a bit confused here.

**Comment by goodanchorage** [comment]
Had 2 people contact me directly about support for 3.2.2. But given the findings it's just not worth the trouble. I'll close this issue. 

Thanks!

**Comment by rgleason** [comment]
Good you closed it.  

The version compiled with Opencpn.lib (for ov3.2.2) without changing the API did not load in v3.2.2  but it did compile and work in v4.0.

When I changed the API to 1.9 and compile with Opencpn.lib for ov3.2.2 I get 23 errors. 

This plugin is for v 4.0 all the way.

Will change the file on Opencpn Beta File Thingie to the previous 4.0 that I had before.

**Comment by rgleason** [comment]
FYI It built with Opencpn.lib for 3.2.2 and the API set as 1.12   but it 
did not work in Opencpnv3.2.2 and it did work in O4.0
When built with Opencpn.lib for 3.2.2 and the API set as 1.9 it did not 
build at all.
